name: bootstrap_sass_example # change this line to have your library name
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  bootstrap_sass: ^4.6.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: ^2.2.1

dependency_overrides:
  bootstrap_sass:
    path: ../
